#!/bin/bash

BASE=$1
RELPATH=$2
FILE=$BASE$RELPATH
QUEUE_FILE="../queue.php"

function encode() {
    name=${FILE::-4}
    if [[ $(mediainfo $FILE | grep "Writing library" | sed -n 2p | cut -d ":" -f 2 | cut -d " " -f 2) != x264 ]]
    then
        /usr/bin/ffmpeg -nostats -nostdin -i $FILE -vcodec libx264 -acodec libmp3lame -map 0:v:0 -map 0:a:0 "${name}.mp4" && /bin/rm $FILE && sed "/<h4><a href=https:\/\/multimedia.xarxacatala.cat\/$RELPATH>$RELPATH<\/a><\/h4>/d" $QUEUE_FILE
    else
        /usr/bin/ffmpeg -nostats -nostdin -i $FILE -vcodec copy -acodec libmp3lame -map 0:v:0 -map 0:a:0 "${name}.mp4" && /bin/rm $FILE && sed -i "/<h4><a href=https:\/\/multimedia.xarxacatala.cat\/$RELPATH>$RELPATH<\/a><\/h4>/d" $QUEUE_FILE
    fi
}
encode
