#!/bin/bash

BASE=$1
RELPATH=$2
FILE=$BASE$RELPATH

function subs_encode() {
    name=${FILE::-4}
    /usr/bin/ffmpeg -nostats -nostdin -i $FILE -map 0:v:0 -map 0:a:0 -vf subtitles=$FILE "${name}.mp4" && /bin/rm $FILE && sed -i "/<h4><a href=https:\/\/multimedia.xarxacatala.cat\/$RELPATH>$RELPATH<\/a><\/h4>/d" $QUEUE_FILE
}
subs_encode
